/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/addressInput`; params?: Router.UnknownInputParams; } | { pathname: `/chooseFromMap`; params?: Router.UnknownInputParams; } | { pathname: `/history`; params?: Router.UnknownInputParams; } | { pathname: `/map`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/multiDestinations`; params?: Router.UnknownInputParams; } | { pathname: `/orderCheck`; params?: Router.UnknownInputParams; } | { pathname: `/orderDetail`; params?: Router.UnknownInputParams; } | { pathname: `/productDetail`; params?: Router.UnknownInputParams; } | { pathname: `/receiverInfo`; params?: Router.UnknownInputParams; } | { pathname: `/senderInfo`; params?: Router.UnknownInputParams; } | { pathname: `/VoucherList`; params?: Router.UnknownInputParams; } | { pathname: `/addChangeDestination`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/four` | `/four`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/three` | `/three`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/addressInput`; params?: Router.UnknownOutputParams; } | { pathname: `/chooseFromMap`; params?: Router.UnknownOutputParams; } | { pathname: `/history`; params?: Router.UnknownOutputParams; } | { pathname: `/map`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/multiDestinations`; params?: Router.UnknownOutputParams; } | { pathname: `/orderCheck`; params?: Router.UnknownOutputParams; } | { pathname: `/orderDetail`; params?: Router.UnknownOutputParams; } | { pathname: `/productDetail`; params?: Router.UnknownOutputParams; } | { pathname: `/receiverInfo`; params?: Router.UnknownOutputParams; } | { pathname: `/senderInfo`; params?: Router.UnknownOutputParams; } | { pathname: `/VoucherList`; params?: Router.UnknownOutputParams; } | { pathname: `/addChangeDestination`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/four` | `/four`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/three` | `/three`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/addressInput${`?${string}` | `#${string}` | ''}` | `/chooseFromMap${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/multiDestinations${`?${string}` | `#${string}` | ''}` | `/orderCheck${`?${string}` | `#${string}` | ''}` | `/orderDetail${`?${string}` | `#${string}` | ''}` | `/productDetail${`?${string}` | `#${string}` | ''}` | `/receiverInfo${`?${string}` | `#${string}` | ''}` | `/senderInfo${`?${string}` | `#${string}` | ''}` | `/VoucherList${`?${string}` | `#${string}` | ''}` | `/addChangeDestination${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/four${`?${string}` | `#${string}` | ''}` | `/four${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/three${`?${string}` | `#${string}` | ''}` | `/three${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/two${`?${string}` | `#${string}` | ''}` | `/two${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/addressInput`; params?: Router.UnknownInputParams; } | { pathname: `/chooseFromMap`; params?: Router.UnknownInputParams; } | { pathname: `/history`; params?: Router.UnknownInputParams; } | { pathname: `/map`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/multiDestinations`; params?: Router.UnknownInputParams; } | { pathname: `/orderCheck`; params?: Router.UnknownInputParams; } | { pathname: `/orderDetail`; params?: Router.UnknownInputParams; } | { pathname: `/productDetail`; params?: Router.UnknownInputParams; } | { pathname: `/receiverInfo`; params?: Router.UnknownInputParams; } | { pathname: `/senderInfo`; params?: Router.UnknownInputParams; } | { pathname: `/VoucherList`; params?: Router.UnknownInputParams; } | { pathname: `/addChangeDestination`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/four` | `/four`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/three` | `/three`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
